language: python

env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: grrVsFD+NUzbNZEv9HXhFh48VKnOWatSh4HRvO/k+DFn8iQvj1mXYXyNM7STOgX3lAxryJHpfcie1UvlE6JLPGvM8TKuq4lqtWlHCaDiNOIiaEp4EGxxhLkSz/Zf7D6501OP1hs/8kFO46QHJteOS0/SXcnIC0Fvq2hDqMb6GUoYKWGyxKwvSfT4AdVPWHEe/p2PNyWAMmJwnx1AwggnsxzDg6zAANCEAiEk7iU+gpNTgXmp+DWo/Av9hglidRjSdq8Fn0x4L+PxMxshJhIbdOB5cFS/Lq1LLBF8yqceht+hAj/pzQnIqE6ALYtXgHUxp/W0BJdJWX16m7TXm4NPWgmgRrRLR/amD+Mp5l1M9UHgwSOdQBU22CkF/hfor0b6ED4Q+Ap6ayy+g6cOp29okGLCMIjXxJU/9rIFjYQ5TFfmD2RvVhUj44e7azGyHNa9goro78mcM9on7a377guODVivVNANPTqm2ZEvLprWmLcz/dlEHFb4ODLvvh4x9hYLPZBF1A9j+qhAGuAFtmOPsPBAJzaSEDAu3DWtwYeGh1+RqagoNhLovB/qfz4YbFygWTj7oQfvmnE0wkAFGqR5EbgLl6o4FKvXl5ZpDj8q/gZdCjwi4VLSTguk0xlIfObLhKq73issjB3Jaxi4Pnl5KcnnhhgtvY3WGx27jMP2yB0=

matrix:
  include:
    - python: 3.6
    - python: 3.7
      # required to run python3.7 on Travis CI
      # https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox-travis
  # Travis by default only clones a 'shallow' repository with --depth=50.
  # When building the distribution packages, we use git to determine the
  # package version string (via setuptools_scm), hence we need to fetch
  # the whole repo, and not just the last 50 commits.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then git fetch --unshallow; fi

script: tox

after_success:
  # if it's a tagged commit, upload distribution packages to PyPI
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "typemytype/booleanOperations" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
        pip install --upgrade twine pip setuptools wheel
        python setup.py sdist
        pip wheel --no-deps --wheel-dir dist .
        twine upload dist/*.whl dist/*.zip
    fi

deploy:
  # deploy to Github Releases on tags
  - provider: releases
    api_key:
      secure: H2rz0E/GjRrRmvf6EYWv7Fyu+y4qU+InGiYlQ6xoyrjmMFCTYiPNW0ysu8893JFILusfO48zzEix7HcumQXtJU16XYwqft9eiWIGzSlP1krusmpQ0yTnuy9wEQcd7fXLEQDfiVZpJxWpC1TtsuIdDqpSUFcHDg4hlvn1IIh+6HwRP6+M5Mprze087ydBCKkO4CvqR4olC7bkSPorRtqUsiUHlUxYFS+R75a8ghqVQbky7ew9/r90zljCBFwYTPEv9tQ7OxnAQiUaAYojceThsBrNP1lH83tOoqB2FkKr9I5dxi5gqNuUsJHh3QK0V59oQCxU+iVFYfrlIZHTBQ+2caxIeWm2k9RkMXXkbg1LyfpORt+5L+NcFNE4WT0DTlYrKnpW+jrak0LEWaI97+15uHahph3vOJgaZrTFvRQZUJTWCNcji2jGbZg+O3pS1Vtd1xEgJ1TcrkOYLYBMrVOywbuQL4sXofLxH3I5RwAenkgm5TwxtuiNxpUkqlEhzJ+GYwWtfb7/qtcLIK7Xn6cDdsQG6XYQMVt+HpCKgRLlrQC8si6l+jZBEtJ7o4IKeYbtybFCe5H3V0jnRFRyncPPdpBavqJ093Pr7fGLvmZuHl551WRtyPlBN4aMGsqvqUSjwr/TxsX5zZ1tQ4QTN2YTmCdeUO6P/fwTBf5p0F3QFo8=
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: typemytype/booleanOperations
      tags: true
      all_branches: true
      python: 3.6
