os:
- osx
env:
  matrix:
  - INSTALL_TYPE='macpython' VERSION=2.7.10 CC=clang CXX=clang++
  - INSTALL_TYPE='macpython' VERSION=3.4.3 CC=clang CXX=clang++
  - INSTALL_TYPE='macpython' VERSION=3.5.0 CC=clang CXX=clang++
install:
- source terryfy/travis_tools.sh
- get_python_environment $INSTALL_TYPE $VERSION venv
- $PIP_CMD install --upgrade wheel
- $PIP_CMD install cython
script:
- $PIP_CMD wheel -v -w . .
after_success:
- $PYTHON_EXE setup.py sdist -d . --formats=gztar,zip
before_deploy:
- export GZTAR=$(ls *.tar.gz)
- export ZIP=$(ls *.zip)
- export WHL=$(ls *.whl)
deploy:
  provider: releases
  api_key:
    secure: H2rz0E/GjRrRmvf6EYWv7Fyu+y4qU+InGiYlQ6xoyrjmMFCTYiPNW0ysu8893JFILusfO48zzEix7HcumQXtJU16XYwqft9eiWIGzSlP1krusmpQ0yTnuy9wEQcd7fXLEQDfiVZpJxWpC1TtsuIdDqpSUFcHDg4hlvn1IIh+6HwRP6+M5Mprze087ydBCKkO4CvqR4olC7bkSPorRtqUsiUHlUxYFS+R75a8ghqVQbky7ew9/r90zljCBFwYTPEv9tQ7OxnAQiUaAYojceThsBrNP1lH83tOoqB2FkKr9I5dxi5gqNuUsJHh3QK0V59oQCxU+iVFYfrlIZHTBQ+2caxIeWm2k9RkMXXkbg1LyfpORt+5L+NcFNE4WT0DTlYrKnpW+jrak0LEWaI97+15uHahph3vOJgaZrTFvRQZUJTWCNcji2jGbZg+O3pS1Vtd1xEgJ1TcrkOYLYBMrVOywbuQL4sXofLxH3I5RwAenkgm5TwxtuiNxpUkqlEhzJ+GYwWtfb7/qtcLIK7Xn6cDdsQG6XYQMVt+HpCKgRLlrQC8si6l+jZBEtJ7o4IKeYbtybFCe5H3V0jnRFRyncPPdpBavqJ093Pr7fGLvmZuHl551WRtyPlBN4aMGsqvqUSjwr/TxsX5zZ1tQ4QTN2YTmCdeUO6P/fwTBf5p0F3QFo8=
  file:
    - "${GZTAR}"
    - "${ZIP}"
    - "${WHL}"
  skip_cleanup: true
  on:
    repo: typemytype/booleanOperations
    tags: true
